// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDstLCEgPjXuLpeTpZykWDv83n3aF_Toew',
    appId: '1:776950903389:android:c26d6dcca285bc057e93b4',
    messagingSenderId: '776950903389',
    projectId: 'cab-rider-4192f',
    databaseURL: 'https://cab-rider-4192f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cab-rider-4192f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHnZdTenGE4Sht2SvKVbynZSZa-GG4pOM',
    appId: '1:776950903389:ios:064cd089e71a6fa37e93b4',
    messagingSenderId: '776950903389',
    projectId: 'cab-rider-4192f',
    databaseURL: 'https://cab-rider-4192f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cab-rider-4192f.appspot.com',
    iosClientId: '776950903389-s4lfnds5sa9fuct9um9knp67gpgqg6lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cabRider',
  );
}
